homeassistant:
  # Name of the location where Home Assistant is running
  name: Simple Docker Example
  # customize:
  #   hello_mqtt.last_message:
  #     custom_ui_state_card: my-custom-hello-mqtt-card
  customize_glob:
    "*.*":
      custom_ui_state_card: my-custom-hello-mqtt-card

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/my-custom-hello-mqtt-card.html

hello_mqtt:

http:
  development: 1
